[tool.poetry]
name = "fastapi-rest"
version = "0.1.0"
description = ""
authors = ["GicheruBenjamin <benjaminnjuguna77@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.6"
uvicorn = "^0.34.0"
sqlalchemy = "^2.0.40"
dotenv = "^0.9.9"
bcrypt = "^4.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
